;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=None
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Message.Crystal",NewTagName="Message.HealthCrystal")
+GameplayTagList=(Tag="Attribute.Vital.Health",DevComment="플레이어가 공격받아 사망하기 전까지 받을 수 있는 피해량")
+GameplayTagList=(Tag="Attribute.Vital.Mana",DevComment="플레이어가 스킬을 사용하기 위해 필요한 자원량")
+GameplayTagList=(Tag="Event.Montage.FireBoll",DevComment="")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Message.ManaCrystal",DevComment="")
+GameplayTagList=(Tag="Message.ManaPotion",DevComment="")

